### ISSUE TITLE
steal-tools fail if main is missing in package.json

### ISSUE THREAD

**Issue by vnen** [stealjs/system-npm#155]
Cracked my head on why the build was failing and after some look around decided to add a `main` property in my `package.json`. Note that `system.main` was already defined, so this should not error out, much less with such a cryptic error.

(Not sure if this is the right place to post this issue, but I think it's related to system-npm).

```
Potentially unhandled rejection [2] TypeError: Cannot read property 'substr' of undefined
    at Object.utils.path.isRelative (file:[...]/node_modules/steal/ext/npm-utils.js:435:16)
```

**Comment by matthewp** [comment]
Thanks!  Will take a look.

**Comment by matthewp** [comment]
Closed by https://github.com/stealjs/system-npm/pull/156
