### ISSUE TITLE
Allow options under "steal"

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#164]
Keep "system" for backwards compat, but allow "steal" to be the package.json object.  No difference otherwise.

**Comment by mjstahl** [comment]
Per conversation with @matthewp today.

Add a helper function to npm-utils.js. Something like:

```js
utils.config = (pkg) => return pkg.steal || pkg.system;
```

Then update the all the code to use the util function as opposed to accessing the pkg.system property directly.

Also update all of the steal docs, and READMEs.

**Comment by pYr0x** [comment]
@mjstahl is there a working branch i can also worked on?

**Comment by mjstahl** [comment]
@pYr0x No sir there is not, so if you wanna go ahead and start one. Be my guest. Haven't had a chance to get to it yet.

**Comment by matthewp** [comment]
Closed by #184
