### ISSUE TITLE
JavaScript files with a period 404

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#2]
because of this line: https://github.com/bitovi/system-npm/blob/master/npm-extension.js#L225

periods are valid in file names and not that uncommon `foo.bar.js`. I ran into this playing around with the extension.  

Why is this check needed?

**Comment by justinbmeyer** [comment]
Is that line different now?  Maybe reference the line in a commit.

**Comment by matthewp** [comment]
Think this is gone now.
