### ISSUE TITLE
Caching package.jsons

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#25]
I wonder if it would be possible to cache package.jsons in local storage (in dev).  This could greatly increase the startup speed.

The only exception would be the root package.json.  We would have to load it every time to see if anything changed. If it has, invalidate the cache.

**Comment by matthewp** [comment]
Thoughts @justinbmeyer?

**Comment by matthewp** [comment]
Actually the absolute simplest thing we could do is cache everything that's not user code.  When a dependency changes invalidate the cache and get everything again.  This could be done with a simple fetch hook.

**Comment by justinbmeyer** [comment]
Yes, but I think that progressive loading of `package.json` might be a better first enhancement.  It will drastically lower the number of requests and JS that needs to be processed.

**Comment by matthewp** [comment]
Why would it lower the number of requests needed for javascript?
