### ISSUE TITLE
browser field example: mocha

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#26]
Mocha is a module that makes heavy use of browserify assumptions, we should try to get it to load.

**Comment by matthewp** [comment]
Browser also supports ignoring modules by marking them as false:

https://gist.github.com/defunctzombie/4339901

**Comment by justinbmeyer** [comment]
For some reason, I thought I implemented this.  I was just going to change the module name to "@empty".

**Comment by matthewp** [comment]
That part was implemented but the normalize hook expects to find a package of which there isn't one for `@empty`

**Comment by matthewp** [comment]
Mocha's browser module is a global using its own commonjs shim. Works fine if set as a global.
