### ISSUE TITLE
How should we handle dependencies pointing at folders?

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#3]
In node it's not uncommon to do `require('lib/foo')` where `lib/foo` is a folder and the module to load is `lib/foo/index.js`. Since we can't detect this it will cause a 404 and the app to not load.  What, if anything, can we do about this?  Can we at least let the user know so they can manually add a path?

**Comment by justinbmeyer** [comment]
Yeah, but I would imagine fetch already does this?  We could add a specific warning.

**Comment by matthewp** [comment]
I think we should retry with `lib/foo/index.js` when this happens.

**Comment by justinbmeyer** [comment]
Yeah, not a bad idea.

**Comment by matthewp** [comment]
Chai is an example of a module that will not load because of this: http://chaijs.com/

We should probably treat 404s as caused by this and retry with `removeJs(address) + "/index.js"`.
