### ISSUE TITLE
Audit popular OS libraries

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#33]
Should do an audit of popular open source libraries and make sure they work. I've tested a few that did not, such as Mocha.

**Comment by matthewp** [comment]
This audit is based on the top [Bower packages](http://bower.io/search/) sorted by stars. They are installed from npm, of course.  I couldn't find a listing of the top NPM browser modules. Will do another audit if a better list can be found.

* Bootstrap **no** #34
* Angular **yes**
* D3 **yes**
* Font-Awesome **yes**
* Backbone **no** (UMD depends on jquery, package.json doesn't)
* animate.css **yes**
* Moment **yes**
* Three.js **yes**
* Normalize.css **yes**
* Semantic-UI (doesn't look like a front-end lib)
* Underscore **yes**
* Chart.js **yes**
* Select2 **no** (possibly #34)
* Skrollr **yes**
* Async **yes**
* Less **no**
* Ratchet **yes**
* purecss **no** (#35)
* Hammer.js **yes**
* Sweet Alert **yes**
* Slick.js **no** (https://github.com/kenwheeler/slick/issues/1152)
* Typeahead.js **no** (https://github.com/twitter/typeahead.js/issues/1143)
* jquery-mobile **no** (https://github.com/jquery/jquery-mobile/issues/8011)

**Comment by matthewp** [comment]
These are just some rather other popular libraries I thought of:

* React **yes**
* Ember **no** (https://github.com/emberjs/ember.js/issues/9354)
* Lodash **yes**
* Ramda **yes**
* Mocha **no** (https://github.com/stealjs/system-npm/issues/26)
* Knockout **yes**
* Modernizr **no** (main points to node code)
* Polymer **no** (main points to node code)

**Comment by whitecolor** [comment]
I'm not sure if it is appropriate. but https://github.com/mixu/minilog tries to load node version in browser
so it needs to be mapped to "minilog/lib/web/console.js", 

is this issue about it?

**Comment by matthewp** [comment]
@whitecolor Thanks!  It should work if their package.json has:

```js
{
  "browser": "./lib/web/console.js"
}
```

This would also make it work with browserify.  Should file an issue for them to add that.

**Comment by whitecolor** [comment]
Ok
https://github.com/mixu/minilog/pull/24

**Comment by matthewp** [comment]
Great, hope they merge.

**Comment by mixu** [comment]
Boom, merged! Thanks.

**Comment by matthewp** [comment]
Looks like it's working, thanks @mixu !

**Comment by whitecolor** [comment]
Try to load `less` in browser `(https://github.com/less/less.js/blob/master/package.json)

it tries to load package dependecies why?

**Comment by matthewp** [comment]
Not sure I understand your question. The reason it doesn't work is because its main points to the Node code.  #40 would fix it. PRs welcome.

**Comment by whitecolor** [comment]
I tried with forked version with `"browser": "./dist/less.js"` field and steal tries load less.js package.json deps.

**Comment by matthewp** [comment]
@whitecolor Created https://github.com/stealjs/system-npm/issues/41 to track that issue.

**Comment by matthewp** [comment]
Ah @whitecolor :)  https://github.com/less/less.js/commit/7cc986e361456ea2ed26589425077b22d7d0442a

Thank you!
