### ISSUE TITLE
Support "jspm" package.json property

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#34]
This is similar to our `system`.

**Comment by matthewp** [comment]
Is this the same as https://github.com/stealjs/system-npm/issues/34 ?

**Comment by whitecolor** [comment]
The old issue!

**Comment by matthewp** [comment]
@whitecolor easy fix though: https://github.com/stealjs/system-npm/blob/master/npm-utils.js#L204

That just needs to also check for pkg.jspm.main. I would put it after the pkg.system and pkg.browser checks as those are priority.

**Comment by whitecolor** [comment]
Ok, I've made a PR

**Comment by matthewp** [comment]
Great, thanks.
