### ISSUE TITLE
support jam in package.json

### ISSUE THREAD

**Issue by whitecolor** [stealjs/system-npm#40]
for example this `package.json` 
https://github.com/less/less.js/blob/master/package.json
contains `jam` as analogy to 'browser'
http://jamjs.org/docs

**Comment by matthewp** [comment]
Yeah, we can support at least the `main` property.

**Comment by matthewp** [comment]
If you want to submit a PR this is where the main is retrieved: https://github.com/stealjs/system-npm/blob/master/npm-utils.js#L183

**Comment by matthewp** [comment]
If you are doing this please also add `jspm.main` because i've seen that a few times.  Priority should be pkg.system.main -> pkg.browser -> pkg.jspm.main -> pkg.jam.main -> pkg.main -> "index".

**Comment by matthewp** [comment]
Going to hold off on this for the moment since less was the main reason and it now has the browser field.

**Comment by matthewp** [comment]
Closed in #122, we now support jam (coming in a steal patch soon)
