### ISSUE TITLE
Contextual Mapping doesn't work with npm-plugin config

### ISSUE THREAD

**Issue by BigAB** [stealjs/system-npm#50]
When using contextual mapping, mapping certain modules only within certain modules, with the system-npm plugin, it throws an error and doesn't work.

Here is a gist you can clone and see for yourself:

[Gist Example of it not working](https://gist.github.com/BigAB/26ea87998cbbd9fddcb2)
\* *ignore the stealconfig.js file in there for now* *

Namely the mapping for `moment-timezone` breaks and throws an error:

```
  "system": {
    "map": {
      "moment": "my-moment",
      "moment-timezone": {
        "moment": "moment_lib"
      }
    },
    "paths": {
      "my-moment": "my-moment.js",
      "moment_lib": "node_modules/moment/min/moment-with-locales.js"
    }
  }
```

It **will work** though, when using stealconfig.js, just change add the following to the script tag in `index.html`:

&lt;script src="node_modules/steal/steal.js" main="main" **config="stealconfig.js"**&gt;&lt;/script&gt;

...which will kick in using the stealconfig.js instead, and everything works okay.

```javascript
steal.config({
    "map": {
      "moment": "my-moment",
      "moment-timezone": {
        "moment": "moment_lib"
      }
    },
    "paths": {
      "my-moment": "my-moment.js",
      "moment_lib": "node_modules/moment/min/moment-with-locales.js",
      "moment-timezone": "node_modules/moment-timezone/moment-timezone.js"
    }
});
```

So the configuration is the same, minus the automatic pathing for the moment-timezone module, but it breaks when using the system-npm plugin.

Please let me know if I can give more details or examples.

**Comment by matthewp** [comment]
Awesome that this worked normally. I'll fix this soon
