### ISSUE TITLE
DocumentJS in package.json causes errors

### ISSUE THREAD

**Issue by marshallswain** [stealjs/system-npm#60]
Having DocumentJS in the package.json dependencies or devDependencies causes a lot of errors, stops build.  Maybe it ought to be added to the list of modules to automatically ignore, along with steal and steal-tools.

Here's a gist with the output:
https://gist.github.com/marshallswain/2ff968cbeef8817e789b

**Comment by matthewp** [comment]
Did ignoring it manually prevent the problem?

**Comment by marshallswain** [comment]
Thanks for asking because I didn't know we could do npmIgnores, yet.  Yes, it worked.  Glad I didn't move things around yet.

**Comment by matthewp** [comment]
Cool, going to leave this open, I would avoid having too many global ignores if possible, and we are going to change the code so that it doesn't automatically start downloading all of the package.jsons anyways.

**Comment by matthewp** [comment]
Going to close this in favor of #41
