### ISSUE TITLE
Make steal-builtins be included by default

### ISSUE THREAD

**Issue by daffl** [stealjs/system-npm#61]
I would like to be able to `require` Node builtins like `events` or `querystring` both of which are quite common to be used on the client as well. Browserify provides shims for those libraries when possible.

**Comment by matthewp** [comment]
If you include [steal-builtins](https://www.npmjs.com/package/steal-builtins) as a dependency these should all work.

**Comment by daffl** [comment]
I thought I tried that and it didn't work. Does it map the module names automatically? Could we just include those by default? What is the difference to the original where it is forked from?

**Comment by matthewp** [comment]
We don't include it by default because it will cause "events" to be global to all packages.  This is what causes it to work: https://github.com/stealjs/node-browser-builtins/blob/master/package.json#L95

if you can create a small breaking example i can look into it.

**Comment by daffl** [comment]
I tried steal-builtins yesterday and got this error when running `import 'steal-builtins';`:

```
Uncaught TypeError: require.resolve is not a function(anonymous function) @ index.js:17(anonymous function) @ index.js:58(anonymous function) @ index.js:58doEval @ steal.js:4824__eval @ steal.js:4794exec @ steal.js:3218$__global.upgradeSystemLoader.loader.instantiate.load.metadata.execute @ steal.js:4055linkDynamicModule @ steal.js:3547link @ steal.js:3407$__global.upgradeSystemLoader.loader.instantiate.Promise.all.then.execute @ steal.js:3726doDynamicExecute @ steal.js:1949link @ steal.js:1997doLink @ steal.js:1771updateLinkSetOnLoad @ steal.js:1819(anonymous function) @ steal.js:1640tryCatchReject @ steal.js:1183runContinuation1 @ steal.js:11427.Fulfilled.when @ steal.js:9307.Pending.run @ steal.js:8213.Scheduler._drain @ steal.js:973.define.drain @ steal.js:62run @ steal.js:268
steal.js:5777 error Error loading "steal-builtins@1.0.0#index" at https://localhost:3030/node_modules/steal-builtins/index.js
```

I still think it would be nice to ship those with `system-npm` by default. If I am using NPM already I probably want to be able to use Node builtins like `require('events').EventEmitter`.

**Comment by matthewp** [comment]
You shouldn't import it, just having it as a dependency is enough to make them work.  I created an example app that uses `events` here: https://github.com/stealjs/steal-builtins-example

**Comment by matthewp** [comment]
@daffl did you figure this out?

**Comment by matthewp** [comment]
This is happening now in 1.0
