### ISSUE TITLE
Error when package.json dependencies contains a module that's also in a child module's deps.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/system-npm#63]
Alexis and I ran into a situation with Steal and QUnit where if you have both `qunit` and  `steal-qunit` as npm dependencies it will cause a browser error: Steal ends up looking for qunit.js in the server root. (localhost:8080/qunit.js)  It looks like it has something to do with the way that the steal-npm plugin handles `steal-qunit` loading its own `qunit` dependency.  Removing `qunit` as a dependency and keeping `steal-qunit` resolved the issue.

This could be the same problem that's occurring for @giltig with steal-mocha (in Gitter).

**Comment by dylanrtt** [comment]
+1 This sounds like an issue I had with steal-mocha a few weeks ago. I never figured out the reason it was looking for mocha files in the server root because it eventually resolved itself after a bunch of changes.

**Comment by matthewp** [comment]
steal-qunit doesn't have a dependency on `qunit`, it has one on `qunitjs`.  Your problem was probably because `qunit` is a node thing and wasn't loading correctly.  #41 should fix this issue.

**Comment by matthewp** [comment]
Going to close for now, as progressively loading package.jsons hopefully fixed this issue. Let me know if not and I'll reopen and take a look.
