### ISSUE TITLE
directories.lib should only effect root module entities if they start with the name of the module.

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/system-npm#7]
If folders/files look like:

```
/
  lib/
    modA.js
  test/
    modA_test.js
```

And _package.json_ looks like:

```
{
  "name": "my-pkg",
  "system": {
    "directories": {
      "lib": "lib"
    }
  }
}
```

A `import "my-pkg/modA"`  will get _lib/modA.js_ but an `import "test/modA_test"` will get _test/modA_test.js_ where currently it gets _lib/test/modA_test.js_.

**Comment by matthewp** [comment]
This is working now.
