### ISSUE TITLE
Support for scoped packages

### ISSUE THREAD

**Issue by ccummings** [stealjs/system-npm#76]
The npm extension breaks when used in a scoped package or when it's used in a package with scoped dependencies.

[Details on scope](https://docs.npmjs.com/misc/scope)

**Comment by matthewp** [comment]
What folder are these put in? If the package is `@foo/bar` is the folder `node_modules/bar` or `node_modules/foo/bar` ?

**Comment by ccummings** [comment]
Scoped packages are grouped together so if I install `@foo/bar` and `@foo/baz`, the structure would be:
```
/node_modules
    /foo
        /bar
        /baz
```

**Comment by matthewp** [comment]
I pushed a breaking test to https://github.com/stealjs/system-npm/commit/34b209ec6d137afc9a143002bf9ce7507c3d7f17, if you could take a look and let me know if the file structure is correct, if the two package.jsons are correct and if the main.js is correct that would be helpful.

**Comment by ccummings** [comment]
Yea that will work.

There are two cases that break right now:

1) Using scoped dependencies
2) Using steal in a scoped package

The test you've constructured is for 1, but I imagine once the npm plugin can parse the scoped package properly the second case will be solved as well.

**Comment by matthewp** [comment]
ah, so if I change the main package `scoped` to `@scoped/package` or something that should cover them both. I'll do that.

**Comment by matthewp** [comment]
Actually scoped packages do get installed with the `@` in the folder name.

**Comment by matthewp** [comment]
Hey @ccummings, I think I have a fix for this. It's in the `scoped` branch.  If you could, would you mind copying this file: https://raw.githubusercontent.com/stealjs/system-npm/scoped/npm-utils.js

into your project's `node_modules/steal/ext` folder and give it a try? That's the only file needed to fix this (I think, hopefully).
