### ISSUE TITLE
Make system-npm work with conditional extension

### ISSUE THREAD

**Issue by matthewp** [stealjs/system-npm#79]
```js
import "packageName/fixtures#?conditions.ok";
```

The plugin will turn this into: `packageName@1.0.0#fixtures` and remove the rest of the parts.

**Comment by matthewp** [comment]
Now that I think about it probably not super hard to fix. Can probably just test if the module name is like `#?` or `#{` and those can be safely ignored. /cc @alexisabril

**Comment by matthewp** [comment]
I think this does now, right @m-mujica ?

**Comment by m-mujica** [comment]
yes, it should.
