### ISSUE TITLE
Setup with SystemJS

### ISSUE THREAD

**Issue by yrns** [stealjs/system-npm#82]
I'm trying to set up system-npm with SystemJS and having trouble getting it to find npm modules. I'm probably missing something obvious. Maybe you could look at a [demo setup I created?] (https://github.com/yrns/systemjs-npm-demo)

I get this:

`Error: XHR error (404 Not Found) loading http://localhost:8080/ramda@0.18.0%23dist/ramda.js`

**Comment by justinbmeyer** [comment]
Are you using our version of SystemJS?  I am not sure system-npm is compatible with the base project.

**Comment by yrns** [comment]
Ah, I see. I assumed SystemJS meant the base project. I had a similar problem with their use of full URLs for module names and live-reload, which system-npm can't fully parse. Easy fix.

**Comment by justinbmeyer** [comment]
Their use of full URLS for module names is why we have forked.  I think it's a huge mistake that the spec is making.  You need module names to make portable applications work the right way.

Eventually, we hope to make our stuff fully spec compliant, but still include module names (by splitting the resolve hook into our normalize / locate).  

Btw, if you haven't already, you might checkout StealJS.  http://stealjs.com/  It includes this and live-reload.
