### ISSUE TITLE
Better error reporting for pasing

### ISSUE THREAD

**Issue by whitecolor** [stealjs/system-npm#98]
I think there is need to add `try catch` here, with some configs there exception occures, and user has no clue where to look at at all:

https://github.com/stealjs/system-npm/blob/master/npm-utils.js#L90

I won't do a PR because not sure where correctly to inject try catch there.

**Comment by justinbmeyer** [comment]
We won't add an arbitrary try catch. Instead, let us know what the error is and we will log warnings or throw better error messages.

**Comment by matthewp** [comment]
Closing for now, let us know if you have more specifics.
